# ============================================================================
# Config file for Quality Control
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# ============================================================================
input_directory: ''
input_pattern: '*.bam'
input_csv: ''
assembler: 'flye'

##############################################################################
# CCS
#
# :Parameters:
#
# - min-rq: Minimum predicted accuracy in [0, 1].
# - min-passes: Minimum number of full-length subreads required to generate CCS for a ZMW
# - max-chunks: Determine maximum number of chunks.
# - options: any options recognised by `ccs` cli
# - threads: Number of threads to use
# - resources: computing resources needed to run the job on a cluster
ccs:
    do: true
    min-rq: 0.7
    min-passes: 0
    max-chunks: 10
    options: ''
    threads: 4
    resources:
        mem: 4G


##############################################################################
# Samtools merge
#
# :Parameters:
#
samtools_merge:
    options: ''
    threads: 4
    resources:
        mem: 4G


##############################################################################
# Bam to Fastq
#
# :Parameters:
# - options: any options recognised by `samtools bam2fq` cli
#
bam_to_fastq:
    options: ''
    threads: 4
    resources:
        mem: 4G


##############################################################################
# Canu v2.1
#
# :Parameters:
#
# - genome_size: An estimate of the size of the genome. Common suffices are allowed, for example, 3.7m or 2.8g.
# - preset: Any preset in this list: ['pacbio', 'pacbio-hifi', 'nanopore']
# - use_grid: let canu run steps on cluster.
# - options: any options recognised by `canu` cli
# - threads: Number of threads to use
canu:
    genome_size: '3.3m'
    preset: 'pacbio'
    use_grid: true 
    options: ''
    threads: 1
    resources:
        mem: 1G

##############################################################################
# Long read correction with canu.
#
# The canu correction step is used by hifiasm and flye. So if you use
# canu, this section is not used at all.
#
# :Parameters:
#
# - do: if unchecked this rule is ignored.
# - preset: Any preset in this list: ['pacbio', 'pacbio-hifi', 'nanopore']
# - genome_size: An estimate of the size of the genome. Common suffices are allowed, for example, 3.7m or 2.8g.
# - use_grid: let canu run steps on cluster.
# - correction_options: any options recognised by `canu -correct` cli
# - trimming_options: any options recognised by `canu -trim cli (do not add --corrected option)`
# - threads: Number of threads to use
canu_correction:
    do: false
    genome_size: '3.3m'
    preset: 'pacbio'
    use_grid: true
    correction_options: ''
    trimming_options: ''
    threads: 1
    resources:
        mem: 1G

##############################################################################
# Hifiasm v0.15.1
#
# :Parameters:
#   
# - options: any options recognised by `canu` cli
# - threads: Number of threads to use
hifiasm:
    options: '-f0 -l0 --n-hap 1'
    threads: 4
    resources:
        mem: 4G


##############################################################################
# Flye
#
# :Parameters:
#  
# - preset: Any preset in this list: ['pacbio-raw', 'pacbio-corr', 'pacbio-hifi', 'nano-raw', 'nano-corr', 'nano-hq']
# - options: any options recognised by `flye` cli
# - threads: Number of threads to use
flye:
    preset: 'pacbio-raw'
    options: ''
    threads: 4
    resources:
        mem: 16G

##############################################################################
# Medaka consensus
#
# Medaka dependencies mess up the environment used to run LORA.
# We advice you to use an apptainer or the docker of medaka.
#
# :Parameters:
#  
# - do: if unchecked, this rule is ignored
# - model: models that can be found by running `medaka tools list_models`
# - options: any options recognised by `medaka_consensus` cli
# - threads: Number of threads to use
medaka_consensus:
    do: true
    model: "r941_min_fast_g303"
    options:
    image: "medaka_1.6.1.img"
    threads: 4
    resources:
        mem: 16G
        partition: gpu
        qos: fast
        gres: gpu:1,gmem:24G


##############################################################################
# Circlator
#
# :Parameters:
#   
# - do: if unchecked, this rule is ignored
# - options: any options recognised by `circlator` cli
# - threads: Number of threads to use
circlator:
    do: false
    options: '--split_all_reads'
    threads: 4
    resources:
        mem: 8G


##############################################################################
# Polypolish
#   Paired-end illumina data are mandatory and illumina prefix name must be the same than
#   your long reads files.
#
# :Parameters:
#   
# - do: if unchecked, this rule is ignored
# - input_directory: path where your illumina data are
# - input_pattern: pattern to retrieve your data
# - input_readtag: explicit readtag to retrieve paired-end
# - options: any options recognised by `polypolish` cli
# - threads: Number of threads to use
polypolish:
    do: false
    input_directory:
    input_pattern: "*.fastq.gz"
    input_readtag: "_R[12]"
    options:
    resources:
        mem: 4G

polypolish_bwa:
    resources:
        mem: 8G

##############################################################################
# SeqKit Sort
#
# :Parameters:
#   
# - threads: Number of threads to use
seqkit_sort:
    threads: 4
    resources:
        mem: 4G

##############################################################################
# Minimap2
#
# :Parameters:
#   
# - preset: Preset for application.
# - options: any options recognised by `minimap2` cli
# - threads: Number of threads to use
minimap2:
    preset: 'map-pb'
    options: ''
    threads: 4
    resources:
        mem: 4G

##############################################################################
# Sequana coverage
#
# :Parameters:
#   
# - do: if unchecked, this rule is ignored
# - options: any options recognised by `sequana_coverage` cli
sequana_coverage:
    do: false
    options: ''
    resources:
        mem: 8G

##############################################################################
# Quast
#
# :Parameters:
#   
# - preset: Preset for application (pacbio/nanopore).
# - options: any options recognised by `quast` cli
# - threads: Number of threads to use
quast:
    preset: 'pacbio'
    options: ''
    threads: 4
    resources:
        mem: 4G

##############################################################################
# Busco
#
# :Parameters:
#   
# - do: if unchecked, this rule is ignored
# - lineage: Specify the name of the BUSCO lineage to be used.
# - options: any options recognised by `busco` cli.
# - threads: Number of threads to use.
busco:
    do: false
    lineage: ''
    options: '--offline'
    threads: 4
    resources:
        mem: 4G


##############################################################################
# Prokka
#
# :Parameters:
#   
# - do: if unchecked, this rule is ignored
# - threads: Number of threads to use.
# - options: any options recognised by `prokka` cli
prokka:
    do: false
    options: ''
    threads: 4
    resources:
        mem: 4G

##############################################################################
# SeqKit Head
#
# :Parameters:
#   
# - n_first: Keep only n first contigs
seqkit_head:
    n_first: 100

##############################################################################
# Blast
#
# :Parameters:
#   
# - do: if unchecked, this rule is ignored
# - db_dir: Path to BLAST databases.
# - evalue: Expectation value (E) threshold for saving hits.
# - options: any options recognised by `blastn` cli (except --outfmt)
# - threads: Number of threads to use.
blast:
    do: false
    blastdb: ''
    evalue: '1e-10'
    options: ' -max_target_seqs 5'
    threads: 4
    resources:
        mem: 12G


##############################################################################
#
onsuccess:
    toclean: " slurm*out lora.rules config.yaml stats.txt "
