type: map
mapping:
    "input_directory":
        type: str
        required: true

    "input_pattern":
        type: str
        required: true

    "input_csv":
        type: str
        required: true

    "assembler":
        type: str
        required: true
        enum: ['canu', 'hifiasm', 'flye']

    "apptainers":
        type: any

    "ccs":
        type: map
        mapping:
            "do":
                type: bool
                required: true
            "max-chunks":
                type: int
                required: true
            "min-rq":
                type: number
                required: true
            "min-passes":
                type: int
                required: true
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "samtools_merge":
        type: map
        mapping:
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true
 
    "bam_to_fastq":
        type: map
        mapping:
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "canu":
        type: map
        mapping:
            "genome_size":
                type: str
                required: true
            "preset":
                type: str
                required: true
                # canu 1.6 used pacbio-raw pacbio-corrected nanaopore-raw and nanopore-corrected
                # canu 1.9 added pacbio-hifi
                # canu 2.1 uses only -pacbio -nanopore and -pacbio-hifi
                enum: ['pacbio', 'pacbio-hifi', 'nanopore']
            "use_grid":
                type: bool
                required: true
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "canu_correction":
        type: map
        mapping:
            "do":
                type: bool
                required: true
            "genome_size":
                type: str
                required: true
            "preset":
                type: str
                required: true
                enum: ['pacbio', 'pacbio-hifi', 'nanopore']
            "use_grid":
                type: bool
                required: true
            "correction_options":
                type: text
                required: false
            "trimming_options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "hifiasm":
        type: map
        mapping:
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true
    
    "flye":
        type: map
        mapping:
            "preset":
                type: str
                required: true
                enum: ['pacbio-raw', 'pacbio-corr', 'pacbio-hifi', 'nano-raw', 'nano-corr', 'nano-hq']
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "medaka_consensus":
        type: map
        func: ext_map_optionnal
        mapping:
            "do":
                type: bool
                required: true
            "model":
                type: str
                required: true
                nullable: false
            "image":
                type: str
                required: true
                nullable: true
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "circlator":
        type: map
        mapping:
            "do":
                type: bool
                required: true
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true
            "data_type":
                type: any
                required: true
                enum: ['pacbio-corrected', 'pacbio-raw']

    "polypolish":
        type: map
        func: ext_map_optionnal
        mapping:
            "do":
                type: bool
                required: true
            "input_directory":
                type: str
                required: true
            "input_pattern":
                type: str
                required: true
            "input_readtag":
                type: str
                required: true
            "options":
                type: text
                required: false
            "resources":
                type: any
                required: true

    "polypolish_bwa":
        type: map
        mapping:
            "resources":
                type: any
                required: true
    
    "seqkit_sort":
        type: map
        mapping:
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "minimap2":
        type: map
        mapping:
            "preset":
                type: str
                required: true
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "sequana_coverage":
        type: map
        mapping:
            "do":
                type: bool
                required: true
            "options":
                type: text
                required: false
            "resources":
                type: any
                required: true

    "quast":
        type: map
        mapping:
            "preset":
                type: str
                enum: ['pacbio', 'nanopore']
                required: true
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "busco":
        type: map
        func: ext_map_optionnal
        mapping:
            "do":
                type: bool
                required: true
            "lineage":
                type: str
                required: true
                nullable: false
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true

    "prokka":
        type: map
        mapping:
            "do":
                type: bool
                required: true
            "options":
                type: text
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true
    
    "seqkit_head":
        type: map
        mapping:
            "n_first":
                type: int
                required: true

    "blast":
        type: map
        func: ext_map_optionnal
        mapping:
            "do":
                type: bool
                required: true
            "blastdb":
                type: str
                required: true
                nullable: false
            "evalue":
                type: str
                required: true
            "options":
                type: str
                required: false
            "threads":
                type: int
                required: true
            "resources":
                type: any
                required: true


    "onsuccess":
        type: map
        mapping:
            "toclean":
                type: text
                required: true
